# Generated by Django 4.0.1 on 2023-06-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_news_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='player_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='player_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='player_name',
            new_name='title',
        ),
    ]
