# Generated by Django 4.0.1 on 2023-06-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_rename_player_description_news_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='News',
            new_name='news',
        ),
    ]
