# Generated by Django 4.0.1 on 2023-06-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0006_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=3000000000000000000000000000000000000000000000000000000000000000000000),
        ),
    ]
